<p><strong>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE DOES NOT INCREASE CHANCES OF
WINNING. INTERNET ACCESS AND VALID EMAIL ADDRESS REQUIRED. VOID WHERE PROHIBITED.</strong></p>

Please read these Official Sweepstakes Rules before entering the Fifth Third Bank Holiday Payback Facebook
Sweepstakes (“Sweepstakes”). By entering the Sweepstakes, you fully and unconditionally agree to be bound
by these Rules during your participation in the Sweepstakes.

SPONSOR: Fifth Third Bank, 38 Fountain Square Plaza, Cincinnati, OH 45263. ADMINISTRATOR: Pathfinders
Advertising & Marketing Group, Inc., 3830 Edison Lakes Parkway, Mishawaka, IN 46545. THIS PROMOTION IS IN NO
WAY SPONSORED, ENDORSED, ADMINISTERED BY, OR ASSOCIATED WITH FACEBOOK. Please direct questions,
comments, or complaints regarding the promotion to the Administrator.

1. ELIGIBILITY: This Sweepstakes is open to legal residents of the United States and the District of Columbia who are
eighteen (18) years of age or older at time of entry or have reached the age of majority within their jurisdiction. This
Sweepstakes is subject to all applicable federal, state, and local laws. Void in Puerto Rico, all U.S. territories and
possessions, Rhode Island, and where prohibited by law. Employees of Fifth Third Bank (“Sponsor”), Pathfinders
Advertising & Marketing Group, Inc. (“Administrator”), and their respective parent and affiliate companies, as well as each
of their immediate family members (spouse, parent, child or sibling) and individuals living in the same households of each
of these individuals, whether or not related, are not eligible to enter or win.

2. TO ENTER: During the Entry Period, as defined in Section 3, visit the Fifth Third Bank Facebook page at http://
www.facebook.com/fifththirdbank and “Like” the page (if you already “Like” the Fifth Third Bank Facebook page, go
directly to the entry form on the Holiday Payback tab). Click on the Holiday Payback tab and follow the instructions to
register and enter. You can opt-in to receive promotional emails from Sponsor but this is NOT required to enter the
Sweepstakes and will NOT affect your odds of winning a prize. To enter without using Facebook, email your name,
address, and phone number to 53HolidayPayback@gmail.com during the Entry Period as defined in Section 3. Limit one
(1) entry per person/email address/household per Entry Period. Entries submitted in excess of the stated limitation will be
void. All entries become the property of Sponsor and will not be returned or verified. The use of automated or third-party
software or websites to enter is prohibited. Entries generated by script, macro, or other automated or mechanical means
or that subvert the entry process will be void. In case of dispute as to the identity of a winner, the winner will be deemed to
be the person who is the registered user of the email address submitted with the winning entry.

3. ENTRY PERIOD: The Sweepstakes begins on Friday, November 9, 2012 and ends on Friday, December 28, 2012.
The sweepstakes consists of eight (8) separate entry periods (an “Entry Period”), each a separate Sweepstakes. Please
refer to Sweepstakes Rule 5 listed below for prizes and schedule for each Entry Period. The Sponsor’s computer is the
official timekeeper for this Sweepstakes.

4. WINNER SELECTION / NOTIFICATION: Winners will be randomly selected from all eligible entries received during
each Entry Period. You are not a winner of any prize until your eligibility and compliance with these Rules has been
confirmed. All entries have the same chance of winning. The odds of winning depend on the number of eligible entries
received during each Entry Period. Administrator will attempt to notify winners on or before the Monday following each
Holiday Payback period, by sending three (3) emails to the email address provided on the entry form. Winner must
respond within one week of the last communication or winner will be disqualified and forfeit his or her interest in all prizes
and, in the case of such forfeiture, no substitute winner will be selected and the prize will be deemed unclaimed. Winners
will be posted to the Holiday Payback Facebook tab on the Fifth Third Bank Facebook page no later than 11 a.m. ET on
the Monday following each Holiday Payback Period. The Sponsor reserves the right not to award the prize. The Sponsor
will not be liable for unsuccessful efforts to notify a winner. All decisions of the Sponsor are final.

5. PRIZES: One (1) prize will be awarded each week that a Holiday Payback occurs. A total of eight (8) winners will be
selected during the Sweepstakes period. Refer to Exhibit A for specific weekly prizes. Total approximate retail value
of all the prizes awarded will not exceed $2,730. Odds of winning a prize are subject to the total number of eligible
entries received for each Entry Period. No substitution of the prize is allowed. Prizes may not be cashed, transferred,
or exchanged. The Sponsor reserves the right to substitute a prize of equal value in the event a prize is unavailable
for any reason. Unclaimed or undeliverable prizes will not be awarded. Additional restrictions may apply. All prizes are

Holiday Payback Facebook Sweepstakes Rules – Draft 2

awarded "AS IS" and without guarantee or warranty of any kind, express or implied, including without limitation, any
implied warranty of merchantability or fitness for a particular purpose. Winner is solely responsible for all taxes on any
prize received, including federal and state income taxes. Any winner who receives at least $600.00 or more in prizes
during a calendar year will receive an IRS Form 1099-MISC and a copy of such form will be filed with the IRS. Winner is
advised to seek independent legal counsel regarding the tax implications with winning and/or claiming any prize. Winner is
not responsible for the shipping costs of any prize. Winner’s name and Facebook profile photo, obtained from the winner’s
Facebook page, will, in Sponsor’s sole discretion, be posted to the Holiday Payback Sweepstakes tab.

*All times are Eastern Standard Time.

6. PUBLICITY: Except where prohibited by law, participation in the Sweepstakes and acceptance of a prize constitutes
winner's consent to the Sponsor and its agents to use winner's name, likeness, photograph, voice, opinions, hometown/
state for promotional/trade purposes in any media, worldwide, without payment or further consideration. This includes, but
is not limited to, posting of winner’s name and photo on the Holiday Payback Sweepstakes tab.

7. GENERAL TERMS AND CONDITIONS: Sponsor reserves the right to modify, suspend, or cancel the Sweepstakes
should tampering, unauthorized intervention, counterfeiting, fraud, technical failures, or other causes beyond Sponsor’s
control corrupt the administration, security, fairness, integrity, or proper play of the Sweepstakes. Sponsor reserves the
right to disqualify any individual suspected of tampering with the entry process or the operation of the Sweepstakes; or
to be acting in any manner deemed by Sponsor to be in violation of the Rules; or to be acting in any manner deemed
by Sponsor to be unsportsmanlike or disruptive, or with intent to annoy, abuse, threaten or harass any other person.
Sponsor reserves the right to modify or clarify these Rules in the event of an occurrence or situation that, in the sole
opinion of the Sponsor, threatens the fairness or integrity of the Sweepstakes. In the event there is a discrepancy between
disclosures and other statements contained in any of the Sweepstakes materials and the terms and conditions of these
Rules, these Rules will prevail, govern, and control. The invalidity of any provision(s) in these Rules does not affect the
validity or enforceability of any other provisions. The failure to enforce any of these Rules shall not constitute a waiver
of that provision. By entering the Sweepstakes, you affirm that you have read and accept these Rules and agree to be
bound by these Rules and by the decisions of the Sponsor, which will be final and binding in all respects. CAUTION: ANY
ATTEMPT TO DELIBERATELY DAMAGE OR UNDERMINE THE LEGITIMATE OPERATION OF THE SWEEPSTAKES
IS A VIOLATION OF CRIMINAL AND CIVIL LAWS AND WILL RESULT IN DISQUALIFICATION FROM PARTICIPATION
IN THE SWEEPSTAKES. SHOULD SUCH AN ATTEMPT BE MADE, SPONSOR RESERVES THE RIGHT TO SEEK
DAMAGES (INCLUDING ATTORNEY FEES) AND OTHER REMEDIES FROM ANY SUCH INDIVIDUAL TO THE
FULLEST EXTENT OF THE LAW.

8. DISPUTES: To the fullest extent permitted by law, entrant agrees that: (1) any and all disputes, claims and causes of
action arising out of or connected with this Sweepstakes or any prize awarded shall be resolved individually, without resort
to any form of class action, and exclusively by the United States District Court for the Southern District of Ohio, Cincinnati
seat of court or the appropriate Ohio state court located in Hamilton County, Ohio; (2) any and all claims, judgments and
awards shall be limited to actual out-of-pocket costs incurred, including costs associated with entering this Sweepstakes,
but in no event attorneys’ fees; and (3) under no circumstances will entrant be permitted to obtain awards for, and entrant
hereby waives all rights to claim, indirect, punitive, incidental and consequential damages and any other damages, other
than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased. All
issues and questions concerning the construction, validity, interpretation and enforceability of these Rules, or the rights
and obligations of the entrant and Sponsor in connection with the Sweepstakes, shall be governed by, and construed in
accordance with, the laws of the State of Ohio without giving effect to any choice of law or conflict of law rules (whether of
the State of Ohio or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the
State of Ohio.

9. RELEASE: Entrants agree to release and hold harmless Sponsor, Administrator, Facebook, and their respective
subsidiaries, affiliates, suppliers, distributors, advertising/promotion agencies, prize suppliers, and each of their respective
parent companies, including officers, directors, employees and agents (collectively, the “Released Parties”) from and
against any claim or cause of action, including, but not limited to, personal injury, death, or damage to or loss of property,
arising out of participation in the Sweepstakes or receipt or use or misuse of any prize. Sponsor and Administrator make
no representation, warranty, or guarantee regarding any prize, directly or indirectly, in fact or in law, including the warranty
of merchantability for intended purpose.

12/21/12
3:00:59 p.m.

12/21/12
5:00:59 p.m.

street names, smart city search, and
a rechargeable lithium-ion battery.
Prize Includes: Amazon Kindle Fire
HD (16 GB) with case. Amazon
Kindle Paperweight with case.

$400

12/28/12
3:00:59 p.m.

12/28/12
5:00:59 p.m.

Prize Includes: 4th Generation Apple
iPod touch, car charger, USB cable,
3.5mm cable, cleaning cloth, dust
cover, audio splitter and $25 iTunes
gift card. Apple iPod Nano 8 GB
(silver) and a $25 iTunes gift card.

$360

Holiday Payback Facebook Sweepstakes Rules – Draft 2

10. LIMITATION OF LIABILITY: The Released Parties are not responsible for (1) any late, lost, incomplete, illegible,
damaged, corrupted, or inaccurate entries; (2) technical, internet, or computer failures of any kind; (3) any incorrect
information, whether caused by entrants, printing errors, or by any of the equipment or programming used to administer
the Sweepstakes; (4) unauthorized human intervention in any part of the entry process or the Sweepstakes; or (5) error in
the interpretation of the offer, administration of the Sweepstakes, or announcement of winners/prizes.

11. PERSONAL INFORMATION: By entering into this contest, entrant is providing information to Sponsor and not to
Facebook, and is subject to Sponsor’s privacy policy https://www.53.com/site/global/privacy-security. Personal data,
such as name and address, may be stored and otherwise used for the purpose of administering the Sweepstakes and
selecting/notifying the winners.

12. WINNER’S LIST: A list of prize winners will be available the week following each Holiday Payback Period. To obtain
a Winner’s List, send a self-addressed, stamped envelope to: Fifth Third Bank Holiday Payback Facebook Sweepstakes
Winners, c/o Pathfinders Advertising & Marketing Group, Inc., 3830 Edison Lakes Parkway, Mishawaka, IN 46545.

©2012 Fifth Third Bank. Member FDIC.